services:
  frontend:
    container_name: "frontend"
    image: "grazen/unilife-web:latest"
    env_file: "frontend.env"
    expose:
      - "3000"
    depends_on:
      - "backend"
    restart: "always"

  backend:
    container_name: "backend"
    image: "grazen/unilife:latest"
    env_file: "backend.env"
    expose:
      - "8080"
    restart: "always"

  caddy:
    container_name: "caddy"
    image: "caddy:latest"
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
      - "caddy_data:/data"
      - "caddy_config:/config"
    depends_on:
      - "frontend"
      - "backend"
    restart: "unless-stopped"

volumes:
  caddy_data:
  caddy_config:
